trigger:
- main
- master
- develop

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cache@2
  inputs:
    key: 'package-lock.json'
    path: 'node_modules'
  displayName: 'Cache node_modules'

- task: gitversion/setup@0
  inputs:
    versionSpec: "5.x"
  displayName: 'Install GitVersion'

- task: gitversion/execute@0
  inputs:
    useConfigFile: True
    configFilePath: "gitversion.yml"
  displayName: 'Calculating version'

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: |
    echo 'Setting package version to: ' + $GitVersion
    git config --global user.email "build-server@codehq.co.za"
    git config --global user.name "build-server"

    npm version $GitVersion --allow-same-version
  displayName: 'Set package version'
  env:
    GitVersion: $(GitVersion.SemVer)

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run test:unit
  displayName: 'npm run test:unit'

- task: Npm@1
  inputs:
    command: 'publish'
    publishEndpoint: 'Code HQ GitHub NPM'